### ISSUE TITLE
Issue with Displaying Relationship Property Text When Null Values Present in Bloom 2.12.0

### ISSUE THREAD

**Issue by jaberrad** [neo4j-apps/neo4j-bloom#77]
If multiple Text items are assigned to a relationship type, and the content for one of the Text items is null for at least one of the relationships, Bloom does not display the entire text.

For example, if the relationship type is `connects_to` and the property values are as follows:
```
A-[connects_to {x: 1, y: null}]->B
B-[connects_to {x: 2, y: null}]->C
C-[connects_to {x: 3, y: 4.56}]->D
```

if we want to display text on the relationships, here is what is expected:
<img width="1010" alt="Screenshot 2024-06-25 at 10 59 22" src="https://github.com/neo4j-devtools/neo4j-bloom/assets/41163614/f6090924-bc60-4825-b526-3524e0be2538">

, and here is the actual result:
<img width="1003" alt="Screenshot 2024-06-25 at 10 59 48" src="https://github.com/neo4j-devtools/neo4j-bloom/assets/41163614/04a05f1e-06ec-472b-86be-d3ce1c829e07">

This is happening in Bloom 2.12.0. Bloom 2.7.0 didn't have this issue.

UPDATE: One way to prevent this is to define rule-based text display and say if the property value is not equal to null, then display it.

**Comment by adriens** [comment]
hi huys, any chance to get it fixed ?
It's a blocking one to go to v2

**Comment by adriens** [comment]
👋 is it fixed in https://github.com/neo4j-devtools/neo4j-bloom/releases/tag/2.25.0 ?

**Comment by ckanz** [comment]
Hi @adriens, thank you for reporting this, we can see the issue on our end as well. I fix is in the works but hadn't been included in the last 2.25.0 release yet

**Comment by adriens** [comment]
Hi @ckanz , thanks a lot for the feedback and the good news.

The next comment will be to validate the fix 🤞 and the _it works on my machine_ 😅

**Comment by adriens** [comment]
Hi guys, I see that [`v2.26.0`](https://github.com/neo4j-devtools/neo4j-bloom/releases/tag/2.26.0) has just been released, but looks like this issue is not part of it : am I right ?

**Comment by ckanz** [comment]
Hi @adriens, that's right, the fix is ready but it missed the cut off for the 2.26.0 release I'm afraid. It will be included in the next release.

**Comment by adriens** [comment]
Hi, is it fixed in https://github.com/neo4j-devtools/neo4j-bloom/releases/tag/2.27.0 ?

**Comment by ckanz** [comment]
Hi @adriens, I'm afraid we had some blockers getting fixes from our visualization library NVL (where to bug originated from and where it has been fixed) into Bloom. As a result, the issue is still present in 2.27.0. I apologise for the long wait for this fix, I am hopeful that it will be included in the next release.

**Comment by adriens** [comment]
> Hi [@adriens](https://github.com/adriens), I'm afraid we had some blockers getting fixes from our visualization library NVL (where to bug originated from and where it has been fixed) into Bloom. As a result, the issue is still present in 2.27.0. I apologise for the long wait for this fix, I am hopeful that it will be included in the next release.

Hi @ckanz , looks like it's not in [`2.28.0`](https://github.com/neo4j-devtools/neo4j-bloom/releases/tag/2.28.0)

**Comment by ckanz** [comment]
Hi @adriens, though it is not explicitly mentioned in the changelog, the fix was included in 2.28.0. I was able to get a sample graph with inconsistent property schema to work:

With the following graph

<img width="351" height="237" alt="Image" src="https://github.com/user-attachments/assets/2c35696b-75b7-438b-88e9-47ecf3ea3370" />

I can visualize all properties and Bloom will still show the ones that are present:

<img width="1076" height="792" alt="Image" src="https://github.com/user-attachments/assets/b2008759-cdee-4dd4-8711-4d62d3d984fe" />

I was able to replicate the bug on 2.27.0 with this graph and can confirm that it is working as expected on 2.8.0.

If you are still experiencing the issue, could you double-check which captions are set the relationship in Bloom in the [styling popup](https://neo4j.com/docs/bloom-user-guide/current/bloom-visual-tour/legend-panel/#_default_styling) and also double-check the exact Bloom version you are using in the [settings drawer](https://neo4j.com/docs/bloom-user-guide/current/bloom-visual-tour/settings-drawer/)?

**Comment by adriens** [comment]
> If you are still experiencing the issue, could you double-check which captions are set the relationship in Bloom in the [styling popup](https://neo4j.com/docs/bloom-user-guide/current/bloom-visual-tour/legend-panel/#_default_styling) and also double-check the exact Bloom version you are using in the [settings drawer](https://neo4j.com/docs/bloom-user-guide/current/bloom-visual-tour/settings-drawer/)?

Sure we will and will let you know 👍
